# Generated by Django 5.2 on 2026-06-10 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntiScamApp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('ios_url', models.CharField(max_length=100)),
                ('android_url', models.CharField(max_length=100)),
                ('huawei_url', models.CharField(max_length=100)),
                ('qr_code', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AntiScamTool',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('top1_contact', models.CharField(max_length=50)),
                ('top1_description', models.CharField(max_length=50)),
                ('top2_contact', models.CharField(max_length=50)),
                ('top2_description', models.CharField(max_length=50)),
                ('top3_contact', models.CharField(max_length=50)),
                ('top3_description', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScamScript',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('realcase', models.CharField(max_length=50)),
                ('img_url', models.CharField(max_length=100)),
                ('scenario1', models.CharField(max_length=50)),
                ('scenario2', models.CharField(max_length=50)),
                ('scenario3', models.CharField(max_length=50)),
                ('scenario4', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsefulContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('institute', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('tool_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='antiscamtools.antiscamtool')),
            ],
        ),
    ]
