# Generated by Django 5.2 on 2026-06-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiscamtools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scamscript',
            name='img_url_s1',
        ),
        migrations.RemoveField(
            model_name='scamscript',
            name='img_url_s2',
        ),
        migrations.RemoveField(
            model_name='scamscript',
            name='img_url_s3',
        ),
        migrations.RemoveField(
            model_name='scamscript',
            name='img_url_s4',
        ),
        migrations.AddField(
            model_name='scamscript',
            name='img_s1',
            field=models.ImageField(default=1, upload_to='antiscamtools/', verbose_name='情景一圖片'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scamscript',
            name='img_s2',
            field=models.ImageField(default=1, upload_to='antiscamtools/', verbose_name='情景二檔案'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scamscript',
            name='img_s3',
            field=models.ImageField(default=1, upload_to='antiscamtools/', verbose_name='情景三檔案'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scamscript',
            name='img_s4',
            field=models.ImageField(default=1, upload_to='antiscamtools/', verbose_name='情景四檔案'),
            preserve_default=False,
        ),
    ]
