# Generated by Django 5.2 on 2026-06-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiscamtools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scamscript',
            old_name='scenario1',
            new_name='img_url_s1',
        ),
        migrations.RenameField(
            model_name='scamscript',
            old_name='scenario2',
            new_name='img_url_s2',
        ),
        migrations.RenameField(
            model_name='scamscript',
            old_name='scenario3',
            new_name='img_url_s3',
        ),
        migrations.RenameField(
            model_name='scamscript',
            old_name='scenario4',
            new_name='img_url_s4',
        ),
        migrations.RemoveField(
            model_name='scamscript',
            name='img_url',
        ),
    ]
