# Generated by Django 5.2 on 2026-06-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='圖片說明（替代文字）')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='圖片檔案')),
                ('seq', models.PositiveIntegerField(default=0, verbose_name='排序（數字愈小愈前面）')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('link_url', models.URLField(blank=True, verbose_name='點擊後連結（選填）')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '輪播圖片',
                'verbose_name_plural': '輪播圖片',
                'ordering': ['seq', 'creation_date'],
            },
        ),
    ]
