# Generated by Django 5.2 on 2026-06-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'ordering': ['seq', 'creation_date'], 'verbose_name': '輪播圖片', 'verbose_name_plural': '輪播圖片'},
        ),
        migrations.RenameField(
            model_name='carouselimage',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='carouselimage',
            old_name='order',
            new_name='seq',
        ),
    ]
