# Generated by Django 5.2 on 2026-06-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidequestion',
            name='answer',
        ),
    ]
