# Generated by Django 5.2 on 2026-06-10 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('speech_url', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('subscriber_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscribes.subscriber')),
            ],
        ),
    ]
