# Generated by Django 5.2 on 2026-06-17 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='主旨')),
                ('content', models.TextField(verbose_name='訊息內容')),
                ('is_read', models.BooleanField(default=False, verbose_name='管理員已讀')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='發送時間')),
                ('reply', models.TextField(blank=True, verbose_name='管理員回覆')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='回覆時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='發送者')),
            ],
            options={
                'verbose_name': '會員訊息',
                'verbose_name_plural': '會員訊息列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='姓氏')),
                ('title', models.CharField(choices=[('先生', '先生'), ('女士', '女士'), ('不便透露', '不便透露')], max_length=10, verbose_name='稱謂')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話號碼')),
                ('birth_year', models.CharField(blank=True, max_length=4, verbose_name='出生年份')),
                ('birth_month', models.CharField(blank=True, max_length=2, verbose_name='出生月份')),
                ('notification_method', models.CharField(choices=[('email', '電郵通知'), ('whatsapp', 'WhatsApp通知')], default='email', max_length=10, verbose_name='通知方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='註冊時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '會員資料',
                'verbose_name_plural': '會員資料列表',
            },
        ),
    ]
