# Generated by Django 5.2 on 2026-06-17 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('img_url', models.CharField(max_length=100)),
                ('detail_title', models.CharField(max_length=100)),
                ('detail_title2', models.CharField(max_length=100)),
                ('detail_desc', models.CharField(max_length=200)),
                ('explanation', models.CharField(max_length=500)),
                ('important1', models.CharField(max_length=100)),
                ('important2', models.CharField(max_length=100)),
                ('important3', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifeFilm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.IntegerField()),
                ('img_url', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('manual_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manuals.manual')),
            ],
        ),
        migrations.CreateModel(
            name='ManualDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('lifefilm_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='manuals.lifefilm')),
            ],
        ),
    ]
