# Generated by Django 5.2 on 2026-06-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualdetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='manualdetail',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='manualdetail',
            name='important1',
        ),
        migrations.RemoveField(
            model_name='manualdetail',
            name='important2',
        ),
        migrations.RemoveField(
            model_name='manualdetail',
            name='important3',
        ),
        migrations.RemoveField(
            model_name='manualdetail',
            name='title',
        ),
        migrations.AddField(
            model_name='manual',
            name='detail_desc',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manual',
            name='detail_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manual',
            name='explanation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manual',
            name='important1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manual',
            name='important2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manual',
            name='important3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
