# Generated by Django 5.2 on 2026-06-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifefilm',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='img_url',
        ),
        migrations.AddField(
            model_name='lifefilm',
            name='image',
            field=models.ImageField(default=1, upload_to='lifefilm/', verbose_name='圖片檔案'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manual',
            name='image',
            field=models.ImageField(default=1, upload_to='manual/', verbose_name='圖片檔案'),
            preserve_default=False,
        ),
    ]
