# Generated by Django 5.2 on 2026-06-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0002_remove_manualdetail_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifefilm',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='manual',
            name='explanation',
            field=models.CharField(max_length=500),
        ),
    ]
