# Generated by Django 5.2 on 2026-06-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0003_alter_lifefilm_description_alter_manual_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='detail_title2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
