# Generated by Django 5.2 on 2026-06-17 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('comm_date', models.DateTimeField(auto_now_add=True)),
                ('district', models.CharField(choices=[('中西區', '中西區'), ('東區', '東區'), ('南區', '南區'), ('灣仔區', '灣仔區'), ('九龍城區', '九龍城區'), ('觀塘區', '觀塘區'), ('深水埗區', '深水埗區'), ('黃大仙區', '黃大仙區'), ('油尖旺區', '油尖旺區'), ('離島區', '離島區'), ('葵青區', '葵青區'), ('北區', '北區'), ('西貢區', '西貢區'), ('沙田區', '沙田區'), ('大埔區', '大埔區'), ('荃灣區', '荃灣區'), ('屯門區', '屯門區'), ('元朗區', '元朗區')], default='', max_length=50)),
                ('fee', models.IntegerField(help_text='課程費用（港幣），0 表示免費')),
                ('category', models.CharField(choices=[('手機班', '手機班'), ('防騙講座', '防騙講座'), ('數位基礎', '數位基礎')], default='手機班', max_length=50)),
                ('course_url', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('poster_url', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', '已報名'), ('cancelled', '已取消')], default='active', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
