# Generated by Django 5.2 on 2026-06-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='course',
            name='poster_img',
            field=models.ImageField(default=1, upload_to='courses/', verbose_name='圖片檔案'),
            preserve_default=False,
        ),
    ]
